"""add_products_and_product_events

Revision ID: 4cc73d8a6e17
Revises: 
Create Date: 2026-04-06 20:15:42.792170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc73d8a6e17'
down_revision: Union[str, None] = '000000000000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Human-readable product name'),
    sa.Column('sku', sa.String(length=200), nullable=True, comment='Stock-keeping unit; unique per company when set'),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True, comment='Full product description – this text gets embedded for RAG'),
    sa.Column('price_json', sa.JSON(), nullable=True, comment='e.g. {"amount": 999, "currency": "INR", "unit": "per month"}'),
    sa.Column('attributes_json', sa.JSON(), nullable=True, comment='Arbitrary key-value product attributes (color, size, warranty …)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weaviate_indexed', sa.Boolean(), nullable=False, comment='True when current DB values are present in Weaviate'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'sku', name='uq_products_company_sku')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_company_id'), 'products', ['company_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_table('product_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True, comment='Null for portal (stateless) queries'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='whatsapp | portal'),
    sa.Column('event_type', sa.String(length=20), nullable=False, comment='retrieved | suggested'),
    sa.Column('query_text', sa.Text(), nullable=True, comment='Original user query (for later analysis)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_events_company_created', 'product_events', ['company_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_product_events_company_id'), 'product_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_events_conversation_id'), 'product_events', ['conversation_id'], unique=False)
    op.create_index('ix_product_events_product_created', 'product_events', ['product_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_product_events_product_id'), 'product_events', ['product_id'], unique=False)
    op.alter_column('conversations', 'detected_language',
               existing_type=sa.VARCHAR(length=20),
               comment='english | hindi | hinglish – last decisive customer language (short/ambiguous messages keep the previous value)',
               existing_comment='english | hindi | hinglish – detected from first message',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'detected_language',
               existing_type=sa.VARCHAR(length=20),
               comment='english | hindi | hinglish – detected from first message',
               existing_comment='english | hindi | hinglish – last decisive customer language (short/ambiguous messages keep the previous value)',
               existing_nullable=True)
    op.drop_index(op.f('ix_product_events_product_id'), table_name='product_events')
    op.drop_index('ix_product_events_product_created', table_name='product_events')
    op.drop_index(op.f('ix_product_events_conversation_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_company_id'), table_name='product_events')
    op.drop_index('ix_product_events_company_created', table_name='product_events')
    op.drop_table('product_events')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_company_id'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
